<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\User;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $adminUser = User::where('email', 'admin@example.com')->first() ?? User::first();

        $clients = [
            ['first_name' => 'Robert', 'last_name' => 'Thompson', 'email' => 'robert.thompson@techwave.com', 'phone' => '+1-415-555-0101', 'company_name' => 'TechWave Solutions', 'website' => 'https://techwave.com', 'address' => '2100 Powell Street, Suite 200', 'city' => 'San Francisco', 'state' => 'CA', 'country' => 'USA', 'postal_code' => '94133', 'status' => 'active', 'notes' => 'Premium enterprise client - 24/7 support'],
            ['first_name' => 'Jennifer', 'last_name' => 'Martinez', 'email' => 'jennifer.martinez@designhub.io', 'phone' => '+1-212-555-0102', 'company_name' => 'DesignHub Studio', 'website' => 'https://designhub.io', 'address' => '350 Fifth Avenue', 'city' => 'New York', 'state' => 'NY', 'country' => 'USA', 'postal_code' => '10118', 'status' => 'active', 'notes' => 'Creative agency - fast approvals needed'],
            ['first_name' => 'David', 'last_name' => 'Chen', 'email' => 'david.chen@globalventures.com', 'phone' => '+1-312-555-0103', 'company_name' => 'Global Ventures Inc', 'website' => 'https://globalventures.com', 'address' => '233 S Wacker Drive', 'city' => 'Chicago', 'state' => 'IL', 'country' => 'USA', 'postal_code' => '60606', 'status' => 'active', 'notes' => 'International client - EST timezone'],
            ['first_name' => 'Emily', 'last_name' => 'Rodriguez', 'email' => 'emily.rodriguez@marketpro.com', 'phone' => '+1-512-555-0104', 'company_name' => 'MarketPro Agency', 'website' => 'https://marketpro.com', 'address' => '701 Brazos Street', 'city' => 'Austin', 'state' => 'TX', 'country' => 'USA', 'postal_code' => '78701', 'status' => 'active', 'notes' => 'Marketing campaigns - monthly approvals'],
            ['first_name' => 'Michael', 'last_name' => 'Williams', 'email' => 'michael.williams@innovatetech.net', 'phone' => '+1-206-555-0105', 'company_name' => 'Innovate Tech Corp', 'website' => 'https://innovatetech.net', 'address' => '2001 8th Avenue', 'city' => 'Seattle', 'state' => 'WA', 'country' => 'USA', 'postal_code' => '98121', 'status' => 'active', 'notes' => 'SaaS company - quarterly reviews'],
            ['first_name' => 'Sarah', 'last_name' => 'Anderson', 'email' => 'sarah.anderson@blueskyconsulting.com', 'phone' => '+1-617-555-0106', 'company_name' => 'BlueSky Consulting', 'website' => 'https://blueskyconsulting.com', 'address' => '100 Summer Street', 'city' => 'Boston', 'state' => 'MA', 'country' => 'USA', 'postal_code' => '02110', 'status' => 'active', 'notes' => 'Management consulting - compliance required'],
            ['first_name' => 'James', 'last_name' => 'Taylor', 'email' => 'james.taylor@digitaledge.io', 'phone' => '+1-303-555-0107', 'company_name' => 'Digital Edge Media', 'website' => 'https://digitaledge.io', 'address' => '1801 California Street', 'city' => 'Denver', 'state' => 'CO', 'country' => 'USA', 'postal_code' => '80202', 'status' => 'active', 'notes' => 'Content creation - weekly deliverables'],
            ['first_name' => 'Amanda', 'last_name' => 'Johnson', 'email' => 'amanda.johnson@greenenergy.com', 'phone' => '+1-503-555-0108', 'company_name' => 'Green Energy Solutions', 'website' => 'https://greenenergy.com', 'address' => '1120 NW Couch Street', 'city' => 'Portland', 'state' => 'OR', 'country' => 'USA', 'postal_code' => '97209', 'status' => 'active', 'notes' => 'Sustainability projects - detailed docs'],
            ['first_name' => 'Christopher', 'last_name' => 'Lee', 'email' => 'christopher.lee@healthtech.com', 'phone' => '+1-404-555-0109', 'company_name' => 'HealthTech Group', 'website' => 'https://healthtech.com', 'address' => '3350 Peachtree Road', 'city' => 'Atlanta', 'state' => 'GA', 'country' => 'USA', 'postal_code' => '30326', 'status' => 'active', 'notes' => 'Healthcare - HIPAA compliant'],
            ['first_name' => 'Jessica', 'last_name' => 'Davis', 'email' => 'jessica.davis@financepros.com', 'phone' => '+1-704-555-0110', 'company_name' => 'Finance Pros LLC', 'website' => 'https://financepros.com', 'address' => '201 South Tryon Street', 'city' => 'Charlotte', 'state' => 'NC', 'country' => 'USA', 'postal_code' => '28202', 'status' => 'active', 'notes' => 'Financial services - audit trail'],
            ['first_name' => 'Daniel', 'last_name' => 'Garcia', 'email' => 'daniel.garcia@creativeworks.studio', 'phone' => '+1-305-555-0111', 'company_name' => 'Creative Works Studio', 'website' => 'https://creativeworks.studio', 'address' => '1450 Brickell Avenue', 'city' => 'Miami', 'state' => 'FL', 'country' => 'USA', 'postal_code' => '33131', 'status' => 'active', 'notes' => 'Video production - quick turnaround'],
            ['first_name' => 'Nicole', 'last_name' => 'Miller', 'email' => 'nicole.miller@edutech.com', 'phone' => '+1-602-555-0112', 'company_name' => 'EduTech Solutions', 'website' => 'https://edutech.com', 'address' => '2390 East Camelback Road', 'city' => 'Phoenix', 'state' => 'AZ', 'country' => 'USA', 'postal_code' => '85016', 'status' => 'active', 'notes' => 'Educational platform - data protection'],
            ['first_name' => 'Matthew', 'last_name' => 'Wilson', 'email' => 'matthew.wilson@retailconnect.com', 'phone' => '+1-214-555-0113', 'company_name' => 'Retail Connect', 'website' => 'https://retailconnect.com', 'address' => '2001 Ross Avenue', 'city' => 'Dallas', 'state' => 'TX', 'country' => 'USA', 'postal_code' => '75201', 'status' => 'active', 'notes' => 'E-commerce - high volume approvals'],
            ['first_name' => 'Ashley', 'last_name' => 'Moore', 'email' => 'ashley.moore@foodservice.com', 'phone' => '+1-702-555-0114', 'company_name' => 'Food Service Group', 'website' => 'https://foodservice.com', 'address' => '3799 Las Vegas Boulevard', 'city' => 'Las Vegas', 'state' => 'NV', 'country' => 'USA', 'postal_code' => '89109', 'status' => 'active', 'notes' => 'Restaurant chain - menu approvals'],
            ['first_name' => 'Ryan', 'last_name' => 'Taylor', 'email' => 'ryan.taylor@constructionpro.com', 'phone' => '+1-713-555-0115', 'company_name' => 'Construction Pro Inc', 'website' => 'https://constructionpro.com', 'address' => '1601 Smith Street', 'city' => 'Houston', 'state' => 'TX', 'country' => 'USA', 'postal_code' => '77002', 'status' => 'active', 'notes' => 'Commercial construction - blueprints'],
            ['first_name' => 'Kimberly', 'last_name' => 'Anderson', 'email' => 'kimberly.anderson@fashionforward.com', 'phone' => '+1-323-555-0116', 'company_name' => 'Fashion Forward Brands', 'website' => 'https://fashionforward.com', 'address' => '8500 Sunset Boulevard', 'city' => 'Los Angeles', 'state' => 'CA', 'country' => 'USA', 'postal_code' => '90069', 'status' => 'active', 'notes' => 'Fashion - seasonal collections'],
            ['first_name' => 'Brandon', 'last_name' => 'Thomas', 'email' => 'brandon.thomas@automotivetech.com', 'phone' => '+1-313-555-0117', 'company_name' => 'Automotive Tech Solutions', 'website' => 'https://automotivetech.com', 'address' => '100 Renaissance Center', 'city' => 'Detroit', 'state' => 'MI', 'country' => 'USA', 'postal_code' => '48243', 'status' => 'active', 'notes' => 'Automotive parts - technical specs'],
            ['first_name' => 'Stephanie', 'last_name' => 'Jackson', 'email' => 'stephanie.jackson@pharmainnovations.com', 'phone' => '+1-215-555-0118', 'company_name' => 'Pharma Innovations', 'website' => 'https://pharmainnovations.com', 'address' => '1500 Market Street', 'city' => 'Philadelphia', 'state' => 'PA', 'country' => 'USA', 'postal_code' => '19102', 'status' => 'active', 'notes' => 'Pharmaceutical - FDA compliance'],
            ['first_name' => 'Kevin', 'last_name' => 'White', 'email' => 'kevin.white@insuranceplus.com', 'phone' => '+1-816-555-0119', 'company_name' => 'Insurance Plus', 'website' => 'https://insuranceplus.com', 'address' => '1100 Walnut Street', 'city' => 'Kansas City', 'state' => 'MO', 'country' => 'USA', 'postal_code' => '64106', 'status' => 'active', 'notes' => 'Insurance - legal review required'],
            ['first_name' => 'Melissa', 'last_name' => 'Harris', 'email' => 'melissa.harris@travelconnect.com', 'phone' => '+1-619-555-0120', 'company_name' => 'Travel Connect Agency', 'website' => 'https://travelconnect.com', 'address' => '550 West B Street', 'city' => 'San Diego', 'state' => 'CA', 'country' => 'USA', 'postal_code' => '92101', 'status' => 'active', 'notes' => 'Travel packages - promo approvals'],
            ['first_name' => 'Brian', 'last_name' => 'Martin', 'email' => 'brian.martin@sportsgear.com', 'phone' => '+1-901-555-0121', 'company_name' => 'Sports Gear Unlimited', 'website' => 'https://sportsgear.com', 'address' => '465 Beale Street', 'city' => 'Memphis', 'state' => 'TN', 'country' => 'USA', 'postal_code' => '38103', 'status' => 'active', 'notes' => 'Sporting goods - product catalogs'],
            ['first_name' => 'Laura', 'last_name' => 'Thompson', 'email' => 'laura.thompson@eventplanners.com', 'phone' => '+1-615-555-0122', 'company_name' => 'Premier Event Planners', 'website' => 'https://eventplanners.com', 'address' => '209 10th Avenue South', 'city' => 'Nashville', 'state' => 'TN', 'country' => 'USA', 'postal_code' => '37203', 'status' => 'active', 'notes' => 'Corporate events - vendor approvals'],
            ['first_name' => 'Jason', 'last_name' => 'Martinez', 'email' => 'jason.martinez@realestatepros.com', 'phone' => '+1-505-555-0123', 'company_name' => 'Real Estate Pros', 'website' => 'https://realestatepros.com', 'address' => '400 Gold Avenue SW', 'city' => 'Albuquerque', 'state' => 'NM', 'country' => 'USA', 'postal_code' => '87102', 'status' => 'active', 'notes' => 'Property listings - marketing materials'],
            ['first_name' => 'Michelle', 'last_name' => 'Robinson', 'email' => 'michelle.robinson@cloudsolutions.io', 'phone' => '+1-408-555-0124', 'company_name' => 'Cloud Solutions Inc', 'website' => 'https://cloudsolutions.io', 'address' => '2211 North First Street', 'city' => 'San Jose', 'state' => 'CA', 'country' => 'USA', 'postal_code' => '95131', 'status' => 'active', 'notes' => 'Cloud infrastructure - service agreements'],
            ['first_name' => 'Steven', 'last_name' => 'Clark', 'email' => 'steven.clark@sustainablebuilding.com', 'phone' => '+1-503-555-0125', 'company_name' => 'Sustainable Building Group', 'website' => 'https://sustainablebuilding.com', 'address' => '1000 SW Broadway', 'city' => 'Portland', 'state' => 'OR', 'country' => 'USA', 'postal_code' => '97205', 'status' => 'inactive', 'notes' => 'On hold - Contract renewal pending'],
        ];

        foreach ($clients as $data) {
            // Use firstOrCreate to make it idempotent
            Client::firstOrCreate(
                ['email' => $data['email']], // Find by email
                array_merge($data, ['created_by' => $adminUser?->id]) // Create with all data
            );
        }

        $this->command->info('Created/verified 25 realistic clients (24 active, 1 inactive)');
    }
}
